spring:
  application:
    name: oauth2-server
  spring:
    application:
      name: oauth2-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://47.101.210.220:3306/video?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Root!!Spring2018
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 8080

mybatis:
  type-aliases-package: com.funtl.oauth2.domain
  mapper-locations: classpath:mapper/*.xml